version: "3.7"

services:
  hepsiburada-case:
    container_name: hepsiburada-case
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
