export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const SORT_PRICE_ASCENDING = "SORT_PRICE_ASCENDING"
export const SORT_PRICE_DESCENDING = "SORT_PRICE_DESCENDING"
export const SORT_DATE_ASCENDING = "SORT_DATE_ASCENDING"
export const SORT_DATE_DESCENDING = "SORT_DATE_DESCENDING"

export const SET_FILTER = "SET_FILTER"